name: Sonar Scan

on:
  workflow_call:

jobs:
  sonar:
    runs-on: java_build

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: SonarCloud Scan
        run: |
          mvn clean verify sonar:sonar \
            -Dsonar.projectKey=r-bit548-1_DevSecops_Pipeline \
            -Dsonar.organization=r-bit548-1 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.branch.name=main \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
