# .github/workflows/sonar.yml
name: Sonar Scan

on:
 workflow_call:

jobs:
  sonar:
    runs-on: java_build
    #needs: build  # Ensures Sonar runs after build succeeds
    steps:
      - name: SonarCloud Scan
        run: mvn sonar:sonar -Dsonar.projectKey=r-bit548_DevSecops_Pipeline -Dsonar.organization=r-bit548 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=03cccd065f4c8e77aa1bc16f6444b05c59478cfa
